downstream_package_name: edd
jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-30-x86_64
    - fedora-31-x86_64
    - fedora-rawhide-x86_64
  trigger: pull_request
specfile_path: edd.spec
synced_files:
- edd.spec
- .packit.yaml
upstream_package_name: edd
